# Project and Eureka Client Configuration
spring:
  application:
    name: cjava-sales
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cjava
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost