# Project and Eureka Client Configuration
spring:
  application:
    name: cjava-client
  config:
    import: optional:configserver:http://localhost:8889
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/cjava
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ahincho
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8085
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost