# Project Configuration
spring:
  application:
    name: cjava-client
  datasource:
    url: jdbc:postgresql://localhost:5432/cjava
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ahincho
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8087